version: '3.8'

services:
  garasje-avlesning:
    build: .
    container_name: garasje-avlesning
    restart: unless-stopped
    ports:
      - "3000:3001"
    volumes:
      # Persistent data storage
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      # Configuration files
      - ./config:/app/config
    environment:
      # Server configuration
      - NODE_ENV=production
      - PORT=3001
      
      # Database
      - DATABASE_PATH=/app/data/readings.db
      
      # File storage
      - UPLOAD_DIR=/app/uploads
      - LOG_DIR=/app/logs
      
      # CORS (adjust based on your domain)
      - CORS_ORIGIN=http://localhost:3000
      
      # Google Sheets (uncomment and configure when ready)
      # - GOOGLE_SERVICE_ACCOUNT_PATH=/app/config/google-service-account.json
      # - GOOGLE_SHEET_ID=your-google-sheet-id
      
      # Rate limiting
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=1000
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Create named volumes for better data management
volumes:
  garasje_data:
    driver: local
  garasje_uploads:
    driver: local
  garasje_logs:
    driver: local

# Optional: Use named volumes instead of bind mounts
# Uncomment the services section below and comment out the volumes section above
# if you prefer named volumes over bind mounts

# services:
#   garasje-avlesning:
#     # ... same configuration as above ...
#     volumes:
#       - garasje_data:/app/data
#       - garasje_uploads:/app/uploads
#       - garasje_logs:/app/logs
#       - ./config:/app/config